### ISSUE TITLE
code stop in function HAL_I2C_IsDeviceReady

### ISSUE THREAD

**Issue by GrazieleRodriguesIo** [Squieler/BME68x-STM32-HAL#1]
Hello, I" trying to using your code with WIO-E5, and, always brake in HAL_I2C_IsDeviceReady.

**Comment by Squieler** [comment]
Hi,

There are few things I would check, since HAL_I2C_IsDeviceReady just checks if the device is avaliable on the I2C line:

1. In the file named "bme68x_necessary_functions.h", at line 32, there is a include line for the HAL library. I would check if I included the right one.
2. I would check the adress of the device and if it is different than the default (Which is 0x77) in the file "bme68x_necessary_functions.c" at line 37.
3. I would check if I configured the I2C peripheral correct for the device.
4. And of course, it is not a bad idea to check all the jumpers/connections etc. for a second time, just to be sure.

These are the things I can think of right now.

**Comment by GrazieleRodriguesIo** [comment]
1. OK
2. I guess in my case is 0x76. https://wiki.seeedstudio.com/Grove-Temperature_Humidity_Pressure_Gas_Sensor_BME680/
3. I'm using I2C2 (15PA and 15PB) because WIO-E5 indicates from the datasheet that the pin available for I2C communication are these. I changed where I had I2C1 in the code to I2C2. https://files.seeedstudio.com/products/113990934/LoRa-E5%20Dev%20Board%20v1.0.pdf
4. I guess yes.

**Comment by Squieler** [comment]
Hi,

For the device's address, you should change BME68X_I2C_ADDR_HIGH to BME68X_I2C_ADDR_LOW in "bme68x_necessary_functions.c" at line 37.

For the I2C peripheral configuration, I can suggest you to use following parameter settings:

- I2C Speed Mode: Standard
- I2C Clock Speed (Hz): 100000
- Clock no stretch mode: disabled
- primary address length section: 7-bit
- dual address acknowledged: disabled
- primary slave address: 0
- general call address detection: disabled

**Comment by GrazieleRodriguesIo** [comment]
still doesn't work :(

**Comment by Squieler** [comment]
It would be great if you can provide more detail for the project like build warnings etc. Or maybe the code you are working on.

**Comment by GrazieleRodriguesIo** [comment]
STM32 basead in this board: https://www.st.com/content/my_st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32cube-mcu-mpu-packages/stm32cubewl.license=1608693595598.product=STM32CubeWL.version=1.0.0.html#overview

error when trying to communicate with I2C, either by entering the is ready to read function or receiving data. 
---------------------------------------------------------------------------------------------------------------------------------------

_static HAL_StatusTypeDef I2C_IsErrorOccurred(I2C_HandleTypeDef *hi2c, uint32_t Timeout, uint32_t Tickstart)
{
  HAL_StatusTypeDef status = HAL_OK;
  uint32_t itflag   = hi2c->Instance->ISR;
  uint32_t error_code = 0;
  uint32_t tickstart = Tickstart;
  uint32_t tmp1;
  HAL_I2C_ModeTypeDef tmp2;

  if (HAL_IS_BIT_SET(itflag, I2C_FLAG_AF))
  {
    __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_AF);

    
    while ((__HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_STOPF) == RESET) && (status == HAL_OK))
    {
      
      if (Timeout != HAL_MAX_DELAY)
      {
        if (((HAL_GetTick() - tickstart) > Timeout) || (Timeout == 0U))
        {
          tmp1 = (uint32_t)(hi2c->Instance->CR2 & I2C_CR2_STOP);
          tmp2 = hi2c->Mode;

       
          if ((__HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_BUSY) != RESET) && \
              (tmp1 != I2C_CR2_STOP) && \
              (tmp2 != HAL_I2C_MODE_SLAVE))
          {
            
            hi2c->Instance->CR2 |= I2C_CR2_STOP;

           
            tickstart = HAL_GetTick();
          }

          while (__HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_STOPF) == RESET)
          {
          
            if ((HAL_GetTick() - tickstart) > I2C_TIMEOUT_STOPF)
            {
              error_code |=HAL_I2C_ERROR_TIMEOUT;

              status = HAL_ERROR;

              break;
            }
          }
        }
      }
    }

    
    if (status == HAL_OK)
    {
      
      __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_STOPF);
    }

    error_code |= HAL_I2C_ERROR_AF;

    status = HAL_ERROR;
  }

  
  itflag = hi2c->Instance->ISR;

 
  if (HAL_IS_BIT_SET(itflag, I2C_FLAG_BERR))
  {
    error_code |= HAL_I2C_ERROR_BERR;

   
    __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_BERR);

    status = HAL_ERROR;
  }

  
  if (HAL_IS_BIT_SET(itflag, I2C_FLAG_OVR))
  {
    error_code |= HAL_I2C_ERROR_OVR;

    
    __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_OVR);

    status = HAL_ERROR;
  }

  
  if (HAL_IS_BIT_SET(itflag, I2C_FLAG_ARLO))
  {
    error_code |= HAL_I2C_ERROR_ARLO;


    __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_ARLO);

    status = HAL_ERROR;
  }

  if (status != HAL_OK)
  {
    
    I2C_Flush_TXDR(hi2c);

 
    I2C_RESET_CR2(hi2c);

    hi2c->ErrorCode |= error_code;
    hi2c->State = HAL_I2C_STATE_READY;
    hi2c->Mode = HAL_I2C_MODE_NONE;

    
    __HAL_UNLOCK(hi2c);
  }

  return status;
}

---------------------------------------------------------------------------------------------------------------------------------------

HAL_StatusTypeDef HAL_I2C_IsDeviceReady(I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Trials,
                                        uint32_t Timeout)
{
  uint32_t tickstart;

  __IO uint32_t I2C_Trials = 0UL;

  FlagStatus tmp1;
  FlagStatus tmp2;

  if (hi2c->State == HAL_I2C_STATE_READY)
  {
    if (__HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_BUSY) == SET)
    {
      return HAL_BUSY;
    }

 
    __HAL_LOCK(hi2c);

    hi2c->State = HAL_I2C_STATE_BUSY;
    hi2c->ErrorCode = HAL_I2C_ERROR_NONE;

    do
    {
      
      hi2c->Instance->CR2 = I2C_GENERATE_START(hi2c->Init.AddressingMode, DevAddress);

      
      tickstart = HAL_GetTick();

      tmp1 = __HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_STOPF);
      tmp2 = __HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_AF);

      while ((tmp1 == RESET) && (tmp2 == RESET))
      {
        if (Timeout != HAL_MAX_DELAY)
        {
          if (((HAL_GetTick() - tickstart) > Timeout) || (Timeout == 0U))
          {
            
            hi2c->State = HAL_I2C_STATE_READY;

            
            hi2c->ErrorCode |= HAL_I2C_ERROR_TIMEOUT;

            
            __HAL_UNLOCK(hi2c);

            return HAL_ERROR;
          }
        }

        tmp1 = __HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_STOPF);
        tmp2 = __HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_AF);
      }

     
      if (__HAL_I2C_GET_FLAG(hi2c, I2C_FLAG_AF) == RESET)
      {
        
        if (I2C_WaitOnFlagUntilTimeout(hi2c, I2C_FLAG_STOPF, RESET, Timeout, tickstart) != HAL_OK)
        {
          return HAL_ERROR;
        }

        
        __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_STOPF);

     
        hi2c->State = HAL_I2C_STATE_READY;

        
        __HAL_UNLOCK(hi2c);

        return HAL_OK;
      }
      else
      {
       
        if (I2C_WaitOnFlagUntilTimeout(hi2c, I2C_FLAG_STOPF, RESET, Timeout, tickstart) != HAL_OK)
        {
          return HAL_ERROR;
        }

       
        __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_AF);

       
        __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_STOPF);
      }

      
      if (I2C_Trials == Trials)
      {
        
        hi2c->Instance->CR2 |= I2C_CR2_STOP;

        
        if (I2C_WaitOnFlagUntilTimeout(hi2c, I2C_FLAG_STOPF, RESET, Timeout, tickstart) != HAL_OK)
        {
          return HAL_ERROR;
        }

       
        __HAL_I2C_CLEAR_FLAG(hi2c, I2C_FLAG_STOPF);
      }

      
      I2C_Trials++;
    } while (I2C_Trials < Trials);

   
    hi2c->State = HAL_I2C_STATE_READY;

   
    hi2c->ErrorCode |= HAL_I2C_ERROR_TIMEOUT;

   
    __HAL_UNLOCK(hi2c);

    return HAL_ERROR;
  }
  else
  {
    return HAL_BUSY;
  }
}

---------------------------------------------------------------------------------------------------------------------------------------

Flag tmp1 and tmp2 still "reset" and i2c state "HAL_I2C_STATE_BUSY" always. 


Files: [BME68x.zip](https://github.com/Squieler/BME68x-STM32-HAL/files/12333953/BME68x.zip)

**Comment by Squieler** [comment]
There is one more thing I need to ask. Which dev board you are using?
Maybe this one: https://www.seeedstudio.com/LoRa-E5-Dev-Kit-p-4868.html
Or this one: https://www.seeedstudio.com/Grove-LoRa-E5-STM32WLE5JC-p-4867.html

If it is neither above, I am wondering the HSE frequency. To check if it is configured correctly.

**Comment by GrazieleRodriguesIo** [comment]
I'm using https://www.seeedstudio.com/LoRa-E5-Dev-Kit-p-4868.html

**Comment by Squieler** [comment]
Hi,

So first, I checked if the clock speed configured correct. In the IOC file, HSE is activated as the clock source.
And it is configured as 8 MHz. After I checked the dev kit's wiki page, realized that it should have been configured as 32 MHz as mentioned in the wiki. (https://wiki.seeedstudio.com/LoRa_E5_Dev_Board/#:~:text=2.%20Clock%20Configuration,supply%3A%20PB0%2DVDD_TCXO )

![image](https://github.com/Squieler/BME68x-STM32-HAL/assets/80160302/0063b8cd-e27f-4d8a-93a2-7301af66522d)

And clock source should be as below:
![image](https://github.com/Squieler/BME68x-STM32-HAL/assets/80160302/6c9f847c-98ab-4929-a1c0-fc9570a51e0f)

Other than that, looks okay.

**Comment by GrazieleRodriguesIo** [comment]
I've tweaked it, but it still doesn't work. Anyway, thank you so much for trying to help. Any suggestions for places I can look for help?

When break: 
![image](https://github.com/Squieler/BME68x-STM32-HAL/assets/139343906/c344197f-bdce-4728-b0be-7b11582b5463)

**Comment by Squieler** [comment]
You can check out https://electronics.stackexchange.com/ for more help.

Wish you best of luck.
